import { StagedSkillKey } from "./types";

export const SKILL_DESCRIPTIONS: Record<StagedSkillKey, string> = {
  frontLever: "Hold your body horizontal, face-up, hanging from a bar with straight arms. A benchmark back/lat strength skill — the foundation most lever training builds toward.",
  backLever: "The mirror of the front lever — body horizontal, face-down, hanging from a bar. Trains the shoulders and back in a stretched, extended position.",
  planche: "Hold your body horizontal, face-down, supported only by your hands — no feet touching anything. One of the toughest pure-strength calisthenics skills, demanding shoulder and core strength plus serious wrist mobility.",
  muscleUp: "A pull-up that transitions straight into a dip, taking you from hanging below the bar to supported above it. Bridges pulling and pushing strength in one explosive movement.",
  handstand: "Balancing upside down on your hands. The gateway skill to almost every inverted or pressing move in calisthenics — as much about balance and shoulder position as raw strength.",
  humanFlag: "Hold your body sideways and horizontal, gripping a vertical pole with both hands. A striking display of lat, shoulder, and core strength together.",
  pistolSquat: "A single-leg squat all the way to full depth, with the other leg held out straight in front of you. Builds serious unilateral leg strength and balance.",
  lSit: "Support your body on your hands (or a bar) with your legs held straight out in front, forming an L shape. A core and hip-flexor staple that underpins many advanced skills.",
  ironCross: "On rings, hold your arms out straight to the sides, body upright — like a cross. One of gymnastics' classic ring strength skills; needs serious pressing/pulling balance through the shoulders.",
  maltese: "On rings or parallettes, hold your body horizontal with arms spread wide to the sides rather than in front. A planche variation that trades some leverage difficulty for extreme shoulder-width demands.",
  oneArmPullUp: "A pull-up performed with a single arm, the other hand free. A serious pulling-strength milestone most people spend years working toward.",
  oneArmHandstand: "A handstand balanced on one hand only. Demands precise balance and a lot of single-arm pressing strength on top of a solid two-hand handstand.",
  dragonFlag: "Lying on a bench, pin your shoulders down and raise your entire straight body into the air, controlling the descent. A brutal core/hip-flexor strength skill.",
  elbowLever: "Balance your whole body on your forearms/elbows planted on the ground, feet off the floor. A core and shoulder-stability skill that's also a stepping stone toward the planche.",
  oneArmPushUp: "A push-up performed with one arm, the other tucked behind your back. Tests unilateral pushing strength and core anti-rotation together.",
  nordicCurl: "Kneeling with your feet anchored, lower your torso toward the floor under control using only your hamstrings, then pull back up. One of the best hamstring-strength builders around.",
  shrimpSquat: "A deep single-leg squat where the non-working leg is bent and held behind you, touching the ground behind your heel at the bottom. Similar territory to the pistol squat but with different mechanics and mobility demands.",
  handstandPushUp: "A push-up performed in a handstand position, lowering your head toward the ground and pressing back up. Builds serious shoulder pressing strength on top of a solid handstand.",
  impossibleDip: "A dip where you start below the bars in a false-grip hang and press all the way up past parallel, gaining height rather than just depth. An advanced ring/bar strength skill.",
  manna: "An extreme compression skill: hold your straight legs up near or past your head while supporting yourself on your hands. Needs both huge compression strength and serious hip/hamstring flexibility.",
  clapPushUp: "An explosive push-up with enough lift to clap your hands together mid-air before landing. Builds upper-body power, not just strength.",
  kipUp: "From lying on your back, use a kicking/hip-snap motion to pop directly up onto your feet. More about timing and coordination than raw strength.",
  backFlip: "A standing backward flip, rotating a full 360° in the air and landing on your feet. A gymnastics/tricking skill — usually learned with spotting or a soft surface first.",
  frontFlip: "A standing forward flip, rotating a full 360° in the air and landing on your feet. Like the back flip, best approached progressively with spotting.",
  windmill: "Swing your body around a bar in a continuous rotation, using momentum and grip control rather than a static hold. A dynamic bar skill that takes practice to time correctly.",
  aroundTheWorld: "A full 360° giant-swing rotation around a bar with your whole body extended. A dynamic, momentum-driven bar skill — thrilling to watch and to land.",
  handstandWalk: "Walking on your hands while balanced in a handstand. Takes the static handstand skill and adds continuous balance and shoulder control on the move.",
  wallWalk: "Starting in a push-up position with feet against a wall, walk your feet up the wall and your hands in toward it until you're in a handstand. A common on-ramp toward freestanding handstand strength.",
  supermanHold: "Lying face-down, lift your arms and legs off the ground simultaneously and hold. A simple but effective lower-back and posterior-chain strengthener.",
  sidePlank: "Balance on one forearm and the side of one foot, body in a straight line. Builds lateral core (oblique) strength and shoulder stability.",
  copenhagenPlank: "A side plank variation where your top leg rests on a bench or support instead of your feet stacking on the floor — heavily loads the inner-thigh (adductor) muscles.",
  bridge: "Arch your body backward from standing (or lying) until your hands and feet are both on the ground, chest open toward the sky. A gymnastic spine-mobility and shoulder-flexibility skill.",
  turkishGetUp: "A slow, multi-step movement from lying on the ground to standing (or back down), typically done holding a weight overhead the whole way. Builds full-body coordination and stability.",
  pikePress: "From a pike position (hips bent, legs straight), press your shoulders up and over into a handstand. A strength-focused way of entering a handstand rather than kicking up.",
  ropeClimb: "Climb a vertical rope using your arms (and often legs) to ascend. A classic grip and pulling-strength test, with a legless version as the advanced form.",
  skinTheCat: "Hanging from a bar, tuck and rotate your legs and hips backward through your arms and behind you, then reverse back. A shoulder-mobility and control skill that also builds toward the back lever.",
  germanHang: "Hang from a bar with your shoulders rotated so your body hangs below with arms overhead behind you, in a deep stretch position. A shoulder flexibility and strength skill, and a prerequisite for skin the cat and back lever work.",
  chestToBarPullUp: "A pull-up where your chest, not just your chin, reaches the bar. Demands more range of motion and back strength than a standard pull-up.",
  wideGripPullUp: "A pull-up performed with hands set wider than shoulder width. Shifts more emphasis onto the outer lats and reduces your leverage advantage.",
  ringMuscleUp: "A muscle-up performed on gymnastic rings instead of a fixed bar. The instability of the rings makes the transition significantly harder to control than on a bar.",
  ninetyDegreePushUp: "A push-up variation held or performed with your body angled so your hips are close to a right angle relative to your arms — a planche-adjacent pushing strength builder.",
  jumpPistol: "A pistol squat performed with an explosive jump at the top instead of a controlled stand. Adds a power component to single-leg squat strength.",
  sissySquat: "Leaning back with knees driving forward, lower your torso toward your heels using just your quads, keeping your body in a straight line. An intense quad-isolation skill.",
  cossackSquat: "A wide-stance lateral squat, shifting your weight fully onto one bent leg while the other stays straight to the side. Builds hip mobility and single-leg strength through a lateral plane.",
  flagPullUp: "Gripping a vertical pole with one hand above the other, pull yourself up sideways along it. A pulling-strength skill that builds directly toward the human flag.",
  lSitPullUp: "A pull-up performed while holding an L-sit position throughout — legs stay extended out in front the whole time. Combines pulling strength with serious core control.",
  typewriterPullUp: "From the top of a pull-up, shift your whole body laterally from one hand to the other while staying at the top, like sliding along a typewriter carriage. Builds unilateral pulling strength and control.",
  toesToBar: "Hanging from a bar, raise your straight legs all the way up until your toes touch the bar. A core and hip-flexor skill common in gymnastics and functional fitness.",
  invertedCross: "Hold an iron cross position but inverted — upside down on rings with arms out to the sides. An advanced ring skill that combines cross strength with an inverted body position.",
  victorianCross: "A deeper, more extreme version of the iron cross where the body is held below horizontal rather than level with the arms. One of the hardest ring strength skills that exists.",
};
